#######################################################
## @author   Md. Emran Hossain                       ##
## @version  1.0                                     ##
## @since    24 MAR, 2023                            ##
#######################################################

spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master-dev.yml
    drop-first: false
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    dbcp2:
      initial-size: 10
      max-total: 50
      min-idle: 2

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: debug
        stat: debug
    com:
      synesisit:
        cp: info
  file:
    name: C:/log/cp/app.log
    max-size: 10MB
    max-history: 0
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"

springdoc:
  swagger-ui:
    path: cp-ui
    tags-sorter: alpha
    operations-sorter: alpha
    docExpansion : none
  api-docs:
    path: /cp-docs

acl:
  url: http://localhost:8080

file:
  fileDir: /src/main/resources/1M-customers.txt
  exportDir: /src/main/resources/export/